baseurl = "http://xiongharry.github.io/"
languageCode = "zh-cn"
title = "小熊谷听"
--theme = "greyshade"
theme = "air"
Paginate = 10

[author]
name = "Harry"
email = "xiongharry@gmail.com"

[programs]
    githubName = "xiongharry"
    jescription = "小熊谷听"
    github_user = "xiongharry"
    excerpt_link = "[阅读全文]"
